# Generated by Django 5.0 on 2025-01-19 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigIntegerField(db_comment='Unix timestamp ID for the model', editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unix Timestamp ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('word', models.CharField(max_length=256, verbose_name='Word')),
                ('definition', models.TextField(blank=True, null=True, verbose_name='Definition')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to=settings.AUTH_USER_MODEL, verbose_name='Created by this user')),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
                'db_table': 'words_words',
            },
        ),
        migrations.CreateModel(
            name='WordTranslation',
            fields=[
                ('id', models.BigIntegerField(db_comment='Unix timestamp ID for the model', editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unix Timestamp ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('translation_text', models.TextField(blank=True, null=True, verbose_name='Translation text')),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean'), ('hi', 'Hindi'), ('ar', 'Arabic'), ('tr', 'Turkish'), ('sv', 'Swedish'), ('no', 'Norwegian'), ('nl', 'Dutch'), ('pl', 'Polish'), ('el', 'Greek'), ('cs', 'Czech'), ('da', 'Danish'), ('fi', 'Finnish'), ('hu', 'Hungarian'), ('ro', 'Romanian'), ('uk', 'Ukrainian'), ('vi', 'Vietnamese'), ('th', 'Thai')], default='en', max_length=5, verbose_name='Language')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='words.word', verbose_name='Word translation')),
            ],
            options={
                'verbose_name': 'Word translation',
                'verbose_name_plural': 'Words translations',
                'db_table': 'words_word_translations',
            },
        ),
    ]
