# Generated by Django 5.0 on 2025-02-02 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='level',
            field=models.CharField(choices=[('A1', 'Begginer'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper Intermediate'), ('C1', 'Advanced'), ('C2', 'Proficiency')], default='B1', max_length=2, verbose_name='Word Level'),
        ),
        migrations.CreateModel(
            name='WordAntonym',
            fields=[
                ('id', models.BigIntegerField(db_comment='Unix timestamp ID for the model', editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unix Timestamp ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('text', models.TextField(verbose_name='Antonym text')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antonyms', to='words.word', verbose_name='Word')),
            ],
            options={
                'verbose_name': 'Word Antonym',
                'verbose_name_plural': 'Word Antonymys',
                'db_table': 'words_word_antonym',
            },
        ),
        migrations.CreateModel(
            name='WordEtymology',
            fields=[
                ('id', models.BigIntegerField(db_comment='Unix timestamp ID for the model', editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unix Timestamp ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('text', models.TextField(verbose_name='Etymology text')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etymologies', to='words.word', verbose_name='Word')),
            ],
            options={
                'verbose_name': 'Word Etymology',
                'verbose_name_plural': 'Word Etymologies',
                'db_table': 'words_word_etymology',
            },
        ),
        migrations.CreateModel(
            name='WordExample',
            fields=[
                ('id', models.BigIntegerField(db_comment='Unix timestamp ID for the model', editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unix Timestamp ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('text', models.TextField(verbose_name='Example text')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='words.word', verbose_name='Word')),
            ],
            options={
                'verbose_name': 'Word Example',
                'verbose_name_plural': 'Word Examples',
                'db_table': 'words_word_example',
            },
        ),
        migrations.CreateModel(
            name='WordImage',
            fields=[
                ('id', models.BigIntegerField(db_comment='Unix timestamp ID for the model', editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unix Timestamp ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('image', models.ImageField(upload_to='uploads/% Y/% m/% d/', verbose_name='Word image')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='words.word', verbose_name='Word')),
            ],
            options={
                'verbose_name': 'Word Image',
                'verbose_name_plural': 'Word Images',
                'db_table': 'words_word_image',
            },
        ),
        migrations.CreateModel(
            name='WordSynonym',
            fields=[
                ('id', models.BigIntegerField(db_comment='Unix timestamp ID for the model', editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unix Timestamp ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('main_word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='words.word', verbose_name='Main word')),
                ('synonym_word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='similar_words', to='words.word', verbose_name='Synonym word')),
            ],
            options={
                'verbose_name': 'Word Synonym',
                'verbose_name_plural': 'Word Synonyms',
                'db_table': 'words_word_synonym',
            },
        ),
    ]
