# Generated by Django 5.0 on 2025-02-09 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigIntegerField(db_comment='Unix timestamp ID for the model', editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unix Timestamp ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(verbose_name='Is active')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is public')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'db_table': 'quizzes_quiz',
            },
        ),
        migrations.CreateModel(
            name='QuizzQuestion',
            fields=[
                ('id', models.BigIntegerField(db_comment='Unix timestamp ID for the model', editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unix Timestamp ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('question', models.TextField(verbose_name='Question')),
                ('is_correct', models.BooleanField(verbose_name='Is correct')),
                ('question_order', models.PositiveIntegerField(verbose_name='Question order')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Quizz Question',
                'verbose_name_plural': 'Quizz Questions',
                'db_table': 'quizzes_quizz_question',
            },
        ),
    ]
