version: '3.8'

services:
  adminer:
    image: adminer
    container_name: adminer-postgres
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - backend
    environment:
        ADMINER_DEFAULT_SERVER: postgres

networks:
  backend:
    external: true