# Generated by Django 5.0 on 2025-02-02 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('words', '0002_word_level_wordantonym_wordetymology_wordexample_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigIntegerField(db_comment='Unix timestamp ID for the model', editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unix Timestamp ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('text', models.TextField(verbose_name='Note text')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'db_table': 'notes_note',
            },
        ),
        migrations.CreateModel(
            name='WordNote',
            fields=[
                ('id', models.BigIntegerField(db_comment='Unix timestamp ID for the model', editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unix Timestamp ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='notes.note', verbose_name='Note')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='words.word', verbose_name='Word')),
            ],
            options={
                'verbose_name': 'Note Word',
                'verbose_name_plural': 'Note Words',
                'db_table': 'notes_note_words',
            },
        ),
    ]
