from django.db import models
from django.utils.translation import gettext_lazy as _

class LanguageEnum(models.TextChoices):
    ENGLISH = 'en', _('English')
    SPANISH = 'es', _('Spanish')
    FRENCH = 'fr', _('French')
    GERMAN = 'de', _('German')
    ITALIAN = 'it', _('Italian')
    PORTUGUESE = 'pt', _('Portuguese')
    CHINESE = 'zh', _('Chinese')
    JAPANESE = 'ja', _('Japanese')
    KOREAN = 'ko', _('Korean')
    HINDI = 'hi', _('Hindi')
    ARABIC = 'ar', _('Arabic')
    TURKISH = 'tr', _('Turkish')
    SWEDISH = 'sv', _('Swedish')
    NORWEGIAN = 'no', _('Norwegian')
    DUTCH = 'nl', _('Dutch')
    POLISH = 'pl', _('Polish')
    GREEK = 'el', _('Greek')
    CZECH = 'cs', _('Czech')
    DANISH = 'da', _('Danish')
    FINNISH = 'fi', _('Finnish')
    HUNGARIAN = 'hu', _('Hungarian')
    ROMANIAN = 'ro', _('Romanian')
    UKRAINIAN = 'uk', _('Ukrainian')
    VIETNAMESE = 'vi', _('Vietnamese')
    THAI = 'th', _('Thai')
