# Generated by Django 5.0 on 2025-02-09 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('words', '0003_usercategory_usertag_wordcategory_wordtag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWordProgress',
            fields=[
                ('id', models.BigIntegerField(db_comment='Unix timestamp ID for the model', editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unix Timestamp ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_learned', models.BooleanField(blank=True, null=True, verbose_name='Is learned')),
                ('is_favorite', models.BooleanField(blank=True, null=True, verbose_name='Is favorite')),
                ('learned_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Learned timestamp')),
                ('last_reviewed_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Last reviewed timestamp')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_progresses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_progresses', to='words.word', verbose_name='Word')),
            ],
            options={
                'verbose_name': 'Student Word Progress',
                'verbose_name_plural': 'Student Word Progresses',
                'db_table': 'students_word_progress',
            },
        ),
    ]
