version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    env_file:
      - ../../.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  
  backup:
    image: postgres:15
    container_name: postgres_backup
    restart: unless-stopped
    env_file:
      - ../../.env
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./backups:/backups
      - ./backup.sh:/backup.sh
    networks:
      - backend
    depends_on:
      - postgres
    command: sh -c " while true; do /backup.sh; sleep 86400; done"

volumes:
  postgres_data:

networks:
  backend:
    external: true